---
title: Image Compression with Principal Component Analysis
author: ''
date: '2018-04-13'
slug: image-compression-with-principal-component-analysis
categories:
  - R
tags: 
  - machine-learning
  - PCA
header:
  caption: ''
  image: ''
image_preview : "imagecompression/compress.jpg"
output:
  blogdown::html_page:
    toc: true
    number_sections: false
    toc_depth: 2
---


<div id="TOC">
<ul>
<li><a href="#loading-pictures-and-standardizing-the-sizes">Loading pictures and standardizing the sizes</a></li>
<li><a href="#the-tour-image.">The <code>tour</code> Image.</a><ul>
<li><a href="#pca">PCA</a></li>
<li><a href="#scree-plot-and-cumulative-variation-plot">Scree Plot and Cumulative Variation Plot</a></li>
<li><a href="#image-reconstruction">Image Reconstruction</a></li>
<li><a href="#image-size-compression">Image Size Compression</a></li>
</ul></li>
<li><a href="#the-no_tour-image">The <code>no_tour</code> Image</a></li>
<li><a href="#the-new-image.">The <code>new</code> Image.</a></li>
<li><a href="#summary">Summary</a></li>
</ul>
</div>

<p>The following images are taken from <a href="https://blog.designcrowd.com/article/549/famous-landmarks-of-the-world-without-people">DesignCrowd</a>.</p>
<p><img src="/img/imagecompression/paris_tourist.jpg" alt="Image with tourist aka tour" /> <img src="/img/paris_no_tourist.jpg" alt="Image with NO tourist aka no_tour" /></p>
<p>This first image is an image with tourists ( I call it as <code>tour</code>) while the second one has no tourist – <code>no_tour</code>.</p>
<p><img src="/img/rome.jpg" alt="Rome" /> This is another <code>new</code> image that is different from the above two.</p>
<p>The goals are:</p>
<ul>
<li>Use PCA to compress the <code>tour</code> image</li>
<li>Test the generalizability of the PC loadings obtained from <code>tour</code> image to other similar image (i.e., the <code>no_tour</code> image) and a very different image (i.e. <code>new</code> image).</li>
</ul>
<div id="loading-pictures-and-standardizing-the-sizes" class="section level1">
<h1>Loading pictures and standardizing the sizes</h1>
<p>First, let’s load the pictures and look at the dimensions.</p>
<pre class="r"><code>library(jpeg)
path = &quot;C:/Users/mirac/Desktop/Work/acadblog2/static/img/imagecompression&quot;
tour = readJPEG(paste(path,&quot;paris_tourist.jpg&quot;, sep = &quot;/&quot;))
no_tour = readJPEG(paste(path,&quot;paris_no_tourist.jpg&quot;, sep = &quot;/&quot;))
new = readJPEG(paste(path,&quot;rome.jpg&quot;, sep = &quot;/&quot;))</code></pre>
<pre class="r"><code>dim(tour); dim(no_tour); dim(new)</code></pre>
<pre><code>## [1] 459 715   3</code></pre>
<pre><code>## [1] 458 715   3</code></pre>
<pre><code>## [1] 500 750   3</code></pre>
<p>The three pistures do not have the same dimensions so let’s resize them to <code>458, 715, 3.</code> The <code>3</code> represents <code>R</code>, <code>G</code>, and <code>B</code>, the three color schemes from the images.</p>
<pre class="r"><code>library(&quot;EBImage&quot;)
# scale to a specific width and height
tour &lt;- resize(tour, w = 458, h = 715)
new &lt;- resize(new, w = 458, h = 715)

# extract the pixel array
tour &lt;- as.array(tour)
new &lt;- as.array(new)</code></pre>
</div>
<div id="the-tour-image." class="section level1">
<h1>The <code>tour</code> Image.</h1>
<div id="pca" class="section level2">
<h2>PCA</h2>
<p>Break down each color scheme into three dataframe and perform PCA.</p>
<pre class="r"><code>rtour = tour[, ,1]
gtour = tour[, ,2]
btour = tour[, ,3]</code></pre>
<pre class="r"><code>prtour = prcomp(rtour, center = FALSE)
pgtour = prcomp(gtour, center = FALSE)
pbtour = prcomp(btour, center = FALSE)

tour.pca = list(prtour, pgtour, pbtour)</code></pre>
</div>
<div id="scree-plot-and-cumulative-variation-plot" class="section level2">
<h2>Scree Plot and Cumulative Variation Plot</h2>
<p>Take a look at the Scree plot of the PCA.</p>
<pre class="r"><code>library(dplyr)
# Create a dataframe for easier plotting
df = data.frame(scheme = rep(c(&quot;R&quot;, &quot;G&quot;, &quot;B&quot;),each =458), 
                index = rep(1:458,  3),
                var = c(prtour$sdev^2,
                        pgtour$sdev^2, 
                        pbtour$sdev^2))

df %&lt;&gt;% group_by(scheme) %&gt;%
  mutate(propvar =100*var/sum(var)) %&gt;%
  mutate(cumsum = cumsum(propvar)) %&gt;%
  ungroup()

#plot
library(ggplot2)
#relevel to make it look nicer
df$scheme = factor(df$scheme,levels(df$scheme)[c(3,2,1)])

df %&gt;% ggplot(aes( x = index, y = propvar, fill = scheme)) + 
    geom_bar(stat=&quot;identity&quot;) + 
    labs(title=&quot;Screeplot of Principal Component&quot;, x =&quot;Principal Component&quot;, 
         y=&quot;% of Variance&quot;) + geom_line()  + 
    scale_x_continuous(limits = c(0,30)) +
    facet_wrap(~scheme)</code></pre>
<div class="figure"><span id="fig:screeplot"></span>
<img src="/project/2018-04-13-image-compression-with-principal-component-analysis_files/figure-html/screeplot-1.png" alt="The **elbow** of the screeplot is between the fourth and the fifth PC" width="672" />
<p class="caption">
Figure 1: The <strong>elbow</strong> of the screeplot is between the fourth and the fifth PC
</p>
</div>
<pre class="r"><code>df %&gt;% ggplot(aes( x = index, y = cumsum, fill = scheme)) + 
    geom_bar(stat=&quot;identity&quot;) + 
    labs(title=&quot;Cumulative Proportion of Variance Explained Principal Component&quot;, x=&quot;Principal Component&quot;, 
         y=&quot;Cumulative % of Variance&quot;) + geom_line() + 
    scale_x_continuous(limits = c(0,30)) +
    facet_wrap(~scheme)</code></pre>
<div class="figure"><span id="fig:cumprop"></span>
<img src="/project/2018-04-13-image-compression-with-principal-component-analysis_files/figure-html/cumprop-1.png" alt="Thirty PCs appear to be good enough to explain most of the variations" width="672" />
<p class="caption">
Figure 2: Thirty PCs appear to be good enough to explain most of the variations
</p>
</div>
<p>It seems like the first 30 PCs have enough proportion of variance covered because the proportion of variance explained is close to 100%.</p>
</div>
<div id="image-reconstruction" class="section level2">
<h2>Image Reconstruction</h2>
<p>Let’s reconstruct the first image. I choose to look at the images constructed from 2, 30, 200, and 300 Prinicipal Components.</p>
<pre class="r"><code># This is the number of desired PCs
pcnum = c(2,30,200, 300)

for(i in pcnum){
    pca.img &lt;- sapply(tour.pca, function(j) {
      compressed.img &lt;- j$x[,1:i] %*% t(j$rotation[,1:i])
    }, simplify = &#39;array&#39;)
  writeJPEG(pca.img, paste(path,&quot;/tour/tour_compressed_&quot;, round(i,0), &#39;_components.jpg&#39;, sep = &#39;&#39;))
}</code></pre>
<p><img src="/img/imagecompression/tour/tour_compressed_2_components.jpg" width="50%" /><img src="/img/imagecompression/tour/tour_compressed_30_components.jpg" width="50%" /><img src="/img/imagecompression/tour/tour_compressed_200_components.jpg" width="50%" /></p>
<div class="figure"><span id="fig:unnamed-chunk-2"></span>
<img src="/img/imagecompression/tour/tour_compressed_300_components.jpg" alt="Compress images using 2, 30, 200 and 300 PCs respectively." width="50%" />
<p class="caption">
Figure 3: Compress images using 2, 30, 200 and 300 PCs respectively.
</p>
</div>
<p>It appears that using 200 PCs is enough to compress the image while maintaining a good quality.</p>
</div>
<div id="image-size-compression" class="section level2">
<h2>Image Size Compression</h2>
<p>But how about the sizes of these images?</p>
<pre class="r"><code>original &lt;- file.info(paste(path,&quot;paris_tourist.jpg&quot;, sep =&quot;/&quot;))$size / 1000

for(i in pcnum){
  filename = paste(&quot;tour_compressed_&quot;,i,&#39;_components.jpg&#39;, sep = &#39;&#39;)
  full.path = paste(path,&quot;tour&quot;,filename,sep = &quot;/&quot;)
  size = file.info(full.path)$size/1000
  cat(filename, &#39;size:&#39;,size,&quot;\n&quot;,
      &quot;Reduction from the original image: &quot;,(original-size)/original*100,&quot;% \n\n&quot; )
}</code></pre>
<pre><code>## tour_compressed_2_components.jpg size: 30.258 
##  Reduction from the original image:  53.07237 % 
## 
## tour_compressed_30_components.jpg size: 55.743 
##  Reduction from the original image:  13.54726 % 
## 
## tour_compressed_200_components.jpg size: 43.244 
##  Reduction from the original image:  32.93216 % 
## 
## tour_compressed_300_components.jpg size: 39.435 
##  Reduction from the original image:  38.8396 %</code></pre>
<p>Surprisingly, the compressed image that uses 30 PCs has the lowest reduction of image size.</p>
</div>
</div>
<div id="the-no_tour-image" class="section level1">
<h1>The <code>no_tour</code> Image</h1>
<p>Now, let’s use a similar image (<code>no_tour</code>) and use the Principal Loadings obtained from the previous step to execute image compression.</p>
<p>The <code>compress ()</code> function is meant for compressing a new image (i.e., image not used in the previous step to obtain Principal Loadings).</p>
<pre class="r"><code>rno_tour = no_tour[, ,1]
gno_tour = no_tour[, ,2]
bno_tour = no_tour[, ,3]

no_tour_rgb = list(rno_tour,gno_tour,bno_tour)

compress &lt;- function(trained_rgb_pca, newrgb, pcnum, dims){
   r_rotate = trained_rgb_pca[[1]]$rotation
   g_rotate = trained_rgb_pca[[2]]$rotation
   b_rotate = trained_rgb_pca[[3]]$rotation
   
   r = newrgb[[1]]
   g = newrgb[[2]]
   b = newrgb[[3]]
   
  pred_r = (r %*% r_rotate)[,1:pcnum] %*% t(r_rotate[,1:pcnum])
  pred_g = (g %*% g_rotate)[,1:pcnum] %*% t(g_rotate[,1:pcnum])
  pred_b = (b %*% b_rotate)[,1:pcnum] %*% t(b_rotate[,1:pcnum])
  
  pred.pca = list(pred_r, pred_g, pred_b)
  pred.array = array(as.numeric(unlist(pred.pca)),dim = dims)
  return(pred.array)
}

for(i in pcnum){
    pca.img = compress(tour.pca, no_tour_rgb, pcnum = i, dims = c( 458, 715,3))
    writeJPEG(pca.img, paste(path,&quot;/no_tour&quot;,&quot;/no_tour_compressed_&quot;, round(i,0), &#39;_components.jpg&#39;, sep = &#39;&#39;))
}</code></pre>
<p><img src="/img/imagecompression/no_tour/no_tour_compressed_2_components.jpg" width="50%" /><img src="/img/imagecompression/no_tour/no_tour_compressed_30_components.jpg" width="50%" /><img src="/img/imagecompression/no_tour/no_tour_compressed_200_components.jpg" width="50%" /></p>
<div class="figure"><span id="fig:unnamed-chunk-6"></span>
<img src="/img/imagecompression/no_tour/no_tour_compressed_300_components.jpg" alt="Compress simialr images to test the generalizability of PCs" width="50%" />
<p class="caption">
Figure 4: Compress simialr images to test the generalizability of PCs
</p>
</div>
<p>One can observe that the last image’s quality is the best out of four (since it uses the most PCs) but it is not even close to a high quality image.</p>
</div>
<div id="the-new-image." class="section level1">
<h1>The <code>new</code> Image.</h1>
<p>We now know that the performance of PCA in image compression is highly useful to its original image but not for a similar image. It’s natural to ask whether it will be worst if a totally unrelated image (such as <code>new</code> image) was used instead. Let’s check it out.</p>
<pre class="r"><code>rnew = new[, ,1]
gnew = new[, ,2]
bnew = new[, ,3]

new_rgb = list(rnew,gnew,bnew)

for (i in pcnum){
    pca.img = compress(tour.pca, new_rgb, pcnum = i, dims = c(458,715, 3))
    writeJPEG(pca.img, paste(path,&quot;/new&quot;,&quot;/new_compressed_&quot;, round(i,0), &#39;_components.jpg&#39;, sep = &#39;&#39;))
}</code></pre>
<p><img src="/img/imagecompression/new/new_compressed_2_components.jpg" width="50%" /><img src="/img/imagecompression/new/new_compressed_30_components.jpg" width="50%" /><img src="/img/imagecompression/new/new_compressed_200_components.jpg" width="50%" /></p>
<div class="figure"><span id="fig:unnamed-chunk-9"></span>
<img src="/img/imagecompression/new/new_compressed_300_components.jpg" alt="Compressing a non-related image using previously extracted PC loadings" width="50%" />
<p class="caption">
Figure 5: Compressing a non-related image using previously extracted PC loadings
</p>
</div>
<p>While the image output does not look exactly like the original image, the main features of the image is clearly shown on it. This is pretty impressive because the machine learns the rules of extracting important information based on only one image <code>tour</code>. One can experiment increase the number of PCs to get a higher resolution image too.</p>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<p>Principal Component Analysis is a great tool for dimension reduction (thus, sinze reduction in this case), extracting important insights, and uncover underlying message of a dataset.</p>
</div>
